spring:
  application:
    name: bike-advisor
  datasource:
    url: jdbc:postgresql://localhost:5432/bikeadvisor
    username: ${BIKE_DB_USER:postgres}
    password: ${BIKE_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

logging:
  level:
    com.bikeadvisor: INFO
